apiVersion: v1
kind: Service
metadata:
  name: time-frontend-service
  namespace: time
spec:
  type: NodePort
  selector:
    app: time-frontend   # Use this selector to find pods to load balance across
  ports:
    - name: http
      port: 3000        # Port exposed within the cluster
      targetPort: 3000  # Port on the pods the service sends traffic to
      nodePort: 30000   # Port accessible externally on each node

