apiVersion: v1
kind: PersistentVolume
metadata:
  name: time-frontend-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: "<ABSOLUTE-PATH-TO-FILES>"