apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: time-frontend-pvc
  namespace: time
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  volumeName: time-frontend-pv # Name of the existing PV to use
